server:
  port: 9999

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: beaconfiregroupproject@gmail.com
    password: wfymnojuvohocphv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://database-1-instance-1.c3ei26ukc461.us-west-1.rds.amazonaws.com:3306/HR_Portal
    username: {DB_USERNAME}
    password: {DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: your-super-secure-secret-key-that-is-very-long-123456
  expiration: 86400000  # 1 day in milliseconds

logging:
  level:
    com.example.auth: INFO
    org.springframework.mail: DEBUG  

