server:
  port: 9001

spring:
  application:
    name: employee-service
  data:
    mongodb:
      uri: mongodb+srv://beaconfire:f80sJ28ch4bvztsE@cluster0.xlrhv.mongodb.net/retryWrites=true&w=majority&appName=Cluster0
      database: humanresource

jwt:
  secret: your-super-secure-secret-key-that-is-very-long-123456
  expiration: 86400000  # 1 day in milliseconds

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

