server:
  port: 9001

spring:
  application:
    name: employee
  data:
    mongodb:
      uri: mongodb+srv://fullstack:DLVVKcvO9yp1JIyk@cluster0.xlrhv.mongodb.net/retryWrites=true&w=majority&appName=Cluster0
      database: humanresource

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

