spring:
  application:
    name: file-service

cloud:
  aws:
    credentials:
      access-key: AKIA2DRT7Q6H5NXCSNS7
      secret-key: $XlhGNWjc484Fxswek9F/1u5kVXWMHZ8ZetYm0AeP
    region:
      static: us-west-1
    s3:
      bucket: hrinfobucket

server:
  port: 9005

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
