spring:
  application:
    name: file-service

cloud:
  aws:
    credentials:
      access-key: AWS_ACCESS_KEY
      secret-key: AWS_SECRET_KEY
    region:
      static: us-west-1
    s3:
      bucket: hrinfobucket

jwt:
  secret: your-super-secure-secret-key-that-is-very-long-123456
  expiration: 86400000  # 1 day in milliseconds

server:
  port: 9005

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
