server:
  port: 9000 // to change later

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/applications/**

        - id: housing-service
          uri: lb://housing-service
          predicates:
            - Path=/api/housing/**

        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/emails/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: logging-service
          uri: lb://logging-service
          predicates:
            - Path=/api/logging/**

        - id: visa-service
          uri: lb://visa-service
          predicates:
            - Path=/api/visas/**

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**

        # - id: eureka
        #   uri: http://localhost:8761
        #   predicates:
        #     - Path=/eureka/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
