server:
  port: 9003

spring:
  datasource:
    url: jdbc:mysql://database-1-instance-1.c3ei26ukc461.us-west-1.rds.amazonaws.com:3306/HR_Portal
    username: admin
    password: "(v?|ABn?aXLuq0Ej<5iX9DgFc:d."
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_schema: HR_Portal
